version: '3.8'

services:
  go-books:
    container_name: backend
    build: backend
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST=db
    ports:
      - 127.0.0.1:8080:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 127.0.0.1:5432:5432

  frontend:
    container_name: frontend
    build: frontend
    depends_on:
      - go-books
    ports:
      - 127.0.0.1:3000:3000
    tty: true
    stdin_open: true

